name = "Nextflow Config"
grammar = "nextflow"
path_suffixes = ["config"]
tab_size = 4
hard_tabs = false
line_comments = ["// "]
block_comment = { start = "/*", end = "*/", prefix = "", tab_size = 0 }
autoclose_before = ",;:)]}"
word_characters = ["$"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "'''", end = "'''", close = true, newline = false },
    { start = "\"\"\"", end = "\"\"\"", close = true, newline = false },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]

decrease_indent_patterns = [
    { pattern = "^\\s*else\\b", valid_after = ["if"] },
    { pattern = "^\\s*(catch|finally)\\b", valid_after = ["try"] },
]
